name: webtest
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  gap:
  fl_chart:
  flutter_lints: ^1.0.4
  shared_preferences: ^2.0.12
  provider: ^6.0.2
  get_it: ^7.2.0
  collapsible_sidebar: ^2.0.1+2
  responsive_builder: ^0.4.2
  responsive_framework: ^0.1.7
  universal_html: ^2.0.8
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans_Regular.ttf
        - asset: assets/fonts/DMSans_Medium.ttf
        - asset: assets/fonts/DMSans_Bold.ttf

    - family: IconlyBold
      fonts:
        - asset: assets/fonts/Iconly_Bold.ttf

    - family: IconlyBroken
      fonts:
        - asset: assets/fonts/Iconly_Light.ttf

  assets:
    - assets/
    - assets/memoji/
    - assets/cards/
